name: navand_cli
description: >
  The command line tool for scaffolding, serving, and building Navand
  applications.
version: 1.0.0-alpha.4
repository: https://github.com/Hawmex/navand_cli
executables:
  navand:
environment:
  sdk: ^3.1.0
dev_dependencies:
  lints: ^2.0.0
dependencies:
  args: ^2.4.2
  build_daemon: ^4.0.0
  collection: ^1.18.0
  dwds: ^19.0.2+1
  io: ^1.0.4
  logging: ^1.2.0
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4
  shelf_static: ^1.1.2
  webdev: ^3.0.7+1
